"""V5: variogram expected-error-reduction (VEER) acquisition. See DESIGN.md."""

from .selection import (
    NestedPolicySpec,
    VeerPolicySpec,
    front_movement_fraction,
    front_probability_weights,
    front_relevance_weights,
    kernel_distance_field,
    kernel_rectangle_distance,
    nested_veer_candidate_scores,
    nested_veer_select_candidate,
    parse_nested_policy,
    parse_veer_policy,
    predicted_depth_profile,
    veer_candidate_scores,
    veer_select_candidate,
)
from .validation import (
    V5_GATED_ARMS,
    V5_NESTED_ARMS,
    V5_VEER_ARMS,
    V5_VEER_POLICIES,
    V5VeerSliceResult,
    run_v5_veer_slice_replay,
    run_v5_veer_stack_validation,
    trailing_endpoint_summary,
)
from .variogram import (
    NestedVariogramFit,
    VariogramPosterior,
    fit_nested_variogram,
    fit_variogram_posterior,
    gamma_nested,
    matern_3_2_correlation,
    tempered_model_weights,
)

__all__ = [
    "NestedPolicySpec",
    "NestedVariogramFit",
    "V5VeerSliceResult",
    "V5_GATED_ARMS",
    "V5_NESTED_ARMS",
    "V5_VEER_ARMS",
    "V5_VEER_POLICIES",
    "VariogramPosterior",
    "VeerPolicySpec",
    "fit_nested_variogram",
    "fit_variogram_posterior",
    "front_movement_fraction",
    "front_probability_weights",
    "front_relevance_weights",
    "gamma_nested",
    "kernel_distance_field",
    "kernel_rectangle_distance",
    "matern_3_2_correlation",
    "nested_veer_candidate_scores",
    "nested_veer_select_candidate",
    "parse_nested_policy",
    "parse_veer_policy",
    "predicted_depth_profile",
    "run_v5_veer_slice_replay",
    "run_v5_veer_stack_validation",
    "tempered_model_weights",
    "trailing_endpoint_summary",
    "veer_candidate_scores",
    "veer_select_candidate",
]
